/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkerIndexRouteImport } from './routes/worker.index'
import { Route as NriIndexRouteImport } from './routes/nri.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as WorkerProfileRouteImport } from './routes/worker.profile'
import { Route as WorkerPassportRouteImport } from './routes/worker.passport'
import { Route as WorkerEarningsRouteImport } from './routes/worker.earnings'
import { Route as WorkerBookingsRouteImport } from './routes/worker.bookings'
import { Route as RegisterWorkerRouteImport } from './routes/register/worker'
import { Route as RegisterNriRouteImport } from './routes/register/nri'
import { Route as RegisterHouseholdRouteImport } from './routes/register/household'
import { Route as NriHistoryRouteImport } from './routes/nri.history'
import { Route as NriBookRouteImport } from './routes/nri.book'
import { Route as AppPassportRouteImport } from './routes/app.passport'
import { Route as AppInsightsRouteImport } from './routes/app.insights'
import { Route as AppBookRouteImport } from './routes/app.book'
import { Route as AppBackupRouteImport } from './routes/app.backup'
import { Route as AppWorkerIdRouteImport } from './routes/app.worker.$id'
import { Route as AppReviewIdRouteImport } from './routes/app.review.$id'
import { Route as AppBookingIdRouteImport } from './routes/app.booking.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerIndexRoute = WorkerIndexRouteImport.update({
  id: '/worker/',
  path: '/worker/',
  getParentRoute: () => rootRouteImport,
} as any)
const NriIndexRoute = NriIndexRouteImport.update({
  id: '/nri/',
  path: '/nri/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerProfileRoute = WorkerProfileRouteImport.update({
  id: '/worker/profile',
  path: '/worker/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerPassportRoute = WorkerPassportRouteImport.update({
  id: '/worker/passport',
  path: '/worker/passport',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerEarningsRoute = WorkerEarningsRouteImport.update({
  id: '/worker/earnings',
  path: '/worker/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerBookingsRoute = WorkerBookingsRouteImport.update({
  id: '/worker/bookings',
  path: '/worker/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterWorkerRoute = RegisterWorkerRouteImport.update({
  id: '/register/worker',
  path: '/register/worker',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterNriRoute = RegisterNriRouteImport.update({
  id: '/register/nri',
  path: '/register/nri',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterHouseholdRoute = RegisterHouseholdRouteImport.update({
  id: '/register/household',
  path: '/register/household',
  getParentRoute: () => rootRouteImport,
} as any)
const NriHistoryRoute = NriHistoryRouteImport.update({
  id: '/nri/history',
  path: '/nri/history',
  getParentRoute: () => rootRouteImport,
} as any)
const NriBookRoute = NriBookRouteImport.update({
  id: '/nri/book',
  path: '/nri/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPassportRoute = AppPassportRouteImport.update({
  id: '/app/passport',
  path: '/app/passport',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/app/insights',
  path: '/app/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBookRoute = AppBookRouteImport.update({
  id: '/app/book',
  path: '/app/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBackupRoute = AppBackupRouteImport.update({
  id: '/app/backup',
  path: '/app/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkerIdRoute = AppWorkerIdRouteImport.update({
  id: '/app/worker/$id',
  path: '/app/worker/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReviewIdRoute = AppReviewIdRouteImport.update({
  id: '/app/review/$id',
  path: '/app/review/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBookingIdRoute = AppBookingIdRouteImport.update({
  id: '/app/booking/$id',
  path: '/app/booking/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/backup': typeof AppBackupRoute
  '/app/book': typeof AppBookRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/passport': typeof AppPassportRoute
  '/nri/book': typeof NriBookRoute
  '/nri/history': typeof NriHistoryRoute
  '/register/household': typeof RegisterHouseholdRoute
  '/register/nri': typeof RegisterNriRoute
  '/register/worker': typeof RegisterWorkerRoute
  '/worker/bookings': typeof WorkerBookingsRoute
  '/worker/earnings': typeof WorkerEarningsRoute
  '/worker/passport': typeof WorkerPassportRoute
  '/worker/profile': typeof WorkerProfileRoute
  '/app/': typeof AppIndexRoute
  '/nri/': typeof NriIndexRoute
  '/worker/': typeof WorkerIndexRoute
  '/app/booking/$id': typeof AppBookingIdRoute
  '/app/review/$id': typeof AppReviewIdRoute
  '/app/worker/$id': typeof AppWorkerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/backup': typeof AppBackupRoute
  '/app/book': typeof AppBookRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/passport': typeof AppPassportRoute
  '/nri/book': typeof NriBookRoute
  '/nri/history': typeof NriHistoryRoute
  '/register/household': typeof RegisterHouseholdRoute
  '/register/nri': typeof RegisterNriRoute
  '/register/worker': typeof RegisterWorkerRoute
  '/worker/bookings': typeof WorkerBookingsRoute
  '/worker/earnings': typeof WorkerEarningsRoute
  '/worker/passport': typeof WorkerPassportRoute
  '/worker/profile': typeof WorkerProfileRoute
  '/app': typeof AppIndexRoute
  '/nri': typeof NriIndexRoute
  '/worker': typeof WorkerIndexRoute
  '/app/booking/$id': typeof AppBookingIdRoute
  '/app/review/$id': typeof AppReviewIdRoute
  '/app/worker/$id': typeof AppWorkerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app/backup': typeof AppBackupRoute
  '/app/book': typeof AppBookRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/passport': typeof AppPassportRoute
  '/nri/book': typeof NriBookRoute
  '/nri/history': typeof NriHistoryRoute
  '/register/household': typeof RegisterHouseholdRoute
  '/register/nri': typeof RegisterNriRoute
  '/register/worker': typeof RegisterWorkerRoute
  '/worker/bookings': typeof WorkerBookingsRoute
  '/worker/earnings': typeof WorkerEarningsRoute
  '/worker/passport': typeof WorkerPassportRoute
  '/worker/profile': typeof WorkerProfileRoute
  '/app/': typeof AppIndexRoute
  '/nri/': typeof NriIndexRoute
  '/worker/': typeof WorkerIndexRoute
  '/app/booking/$id': typeof AppBookingIdRoute
  '/app/review/$id': typeof AppReviewIdRoute
  '/app/worker/$id': typeof AppWorkerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app/backup'
    | '/app/book'
    | '/app/insights'
    | '/app/passport'
    | '/nri/book'
    | '/nri/history'
    | '/register/household'
    | '/register/nri'
    | '/register/worker'
    | '/worker/bookings'
    | '/worker/earnings'
    | '/worker/passport'
    | '/worker/profile'
    | '/app/'
    | '/nri/'
    | '/worker/'
    | '/app/booking/$id'
    | '/app/review/$id'
    | '/app/worker/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/backup'
    | '/app/book'
    | '/app/insights'
    | '/app/passport'
    | '/nri/book'
    | '/nri/history'
    | '/register/household'
    | '/register/nri'
    | '/register/worker'
    | '/worker/bookings'
    | '/worker/earnings'
    | '/worker/passport'
    | '/worker/profile'
    | '/app'
    | '/nri'
    | '/worker'
    | '/app/booking/$id'
    | '/app/review/$id'
    | '/app/worker/$id'
  id:
    | '__root__'
    | '/'
    | '/app/backup'
    | '/app/book'
    | '/app/insights'
    | '/app/passport'
    | '/nri/book'
    | '/nri/history'
    | '/register/household'
    | '/register/nri'
    | '/register/worker'
    | '/worker/bookings'
    | '/worker/earnings'
    | '/worker/passport'
    | '/worker/profile'
    | '/app/'
    | '/nri/'
    | '/worker/'
    | '/app/booking/$id'
    | '/app/review/$id'
    | '/app/worker/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppBackupRoute: typeof AppBackupRoute
  AppBookRoute: typeof AppBookRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppPassportRoute: typeof AppPassportRoute
  NriBookRoute: typeof NriBookRoute
  NriHistoryRoute: typeof NriHistoryRoute
  RegisterHouseholdRoute: typeof RegisterHouseholdRoute
  RegisterNriRoute: typeof RegisterNriRoute
  RegisterWorkerRoute: typeof RegisterWorkerRoute
  WorkerBookingsRoute: typeof WorkerBookingsRoute
  WorkerEarningsRoute: typeof WorkerEarningsRoute
  WorkerPassportRoute: typeof WorkerPassportRoute
  WorkerProfileRoute: typeof WorkerProfileRoute
  AppIndexRoute: typeof AppIndexRoute
  NriIndexRoute: typeof NriIndexRoute
  WorkerIndexRoute: typeof WorkerIndexRoute
  AppBookingIdRoute: typeof AppBookingIdRoute
  AppReviewIdRoute: typeof AppReviewIdRoute
  AppWorkerIdRoute: typeof AppWorkerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker/': {
      id: '/worker/'
      path: '/worker'
      fullPath: '/worker/'
      preLoaderRoute: typeof WorkerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nri/': {
      id: '/nri/'
      path: '/nri'
      fullPath: '/nri/'
      preLoaderRoute: typeof NriIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker/profile': {
      id: '/worker/profile'
      path: '/worker/profile'
      fullPath: '/worker/profile'
      preLoaderRoute: typeof WorkerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker/passport': {
      id: '/worker/passport'
      path: '/worker/passport'
      fullPath: '/worker/passport'
      preLoaderRoute: typeof WorkerPassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker/earnings': {
      id: '/worker/earnings'
      path: '/worker/earnings'
      fullPath: '/worker/earnings'
      preLoaderRoute: typeof WorkerEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker/bookings': {
      id: '/worker/bookings'
      path: '/worker/bookings'
      fullPath: '/worker/bookings'
      preLoaderRoute: typeof WorkerBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/worker': {
      id: '/register/worker'
      path: '/register/worker'
      fullPath: '/register/worker'
      preLoaderRoute: typeof RegisterWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/nri': {
      id: '/register/nri'
      path: '/register/nri'
      fullPath: '/register/nri'
      preLoaderRoute: typeof RegisterNriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/household': {
      id: '/register/household'
      path: '/register/household'
      fullPath: '/register/household'
      preLoaderRoute: typeof RegisterHouseholdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nri/history': {
      id: '/nri/history'
      path: '/nri/history'
      fullPath: '/nri/history'
      preLoaderRoute: typeof NriHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nri/book': {
      id: '/nri/book'
      path: '/nri/book'
      fullPath: '/nri/book'
      preLoaderRoute: typeof NriBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/passport': {
      id: '/app/passport'
      path: '/app/passport'
      fullPath: '/app/passport'
      preLoaderRoute: typeof AppPassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/insights': {
      id: '/app/insights'
      path: '/app/insights'
      fullPath: '/app/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/book': {
      id: '/app/book'
      path: '/app/book'
      fullPath: '/app/book'
      preLoaderRoute: typeof AppBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/backup': {
      id: '/app/backup'
      path: '/app/backup'
      fullPath: '/app/backup'
      preLoaderRoute: typeof AppBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/worker/$id': {
      id: '/app/worker/$id'
      path: '/app/worker/$id'
      fullPath: '/app/worker/$id'
      preLoaderRoute: typeof AppWorkerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/review/$id': {
      id: '/app/review/$id'
      path: '/app/review/$id'
      fullPath: '/app/review/$id'
      preLoaderRoute: typeof AppReviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/booking/$id': {
      id: '/app/booking/$id'
      path: '/app/booking/$id'
      fullPath: '/app/booking/$id'
      preLoaderRoute: typeof AppBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppBackupRoute: AppBackupRoute,
  AppBookRoute: AppBookRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppPassportRoute: AppPassportRoute,
  NriBookRoute: NriBookRoute,
  NriHistoryRoute: NriHistoryRoute,
  RegisterHouseholdRoute: RegisterHouseholdRoute,
  RegisterNriRoute: RegisterNriRoute,
  RegisterWorkerRoute: RegisterWorkerRoute,
  WorkerBookingsRoute: WorkerBookingsRoute,
  WorkerEarningsRoute: WorkerEarningsRoute,
  WorkerPassportRoute: WorkerPassportRoute,
  WorkerProfileRoute: WorkerProfileRoute,
  AppIndexRoute: AppIndexRoute,
  NriIndexRoute: NriIndexRoute,
  WorkerIndexRoute: WorkerIndexRoute,
  AppBookingIdRoute: AppBookingIdRoute,
  AppReviewIdRoute: AppReviewIdRoute,
  AppWorkerIdRoute: AppWorkerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
